import { SignClient } from "@walletconnect/sign-client/dist/types/client";
import Head from "next/head";
import { useEffect, useState } from "react";
import { useWalletConnect } from "../utils/useWalletConnect";
import WalletConnectButton from "../components/WalletConnectButton";

export default function Home() {
	const { client, init } = useWalletConnect();
	const [signClient, setSignClient] = useState<SignClient>();

	useEffect(() => {
		init();
	}, [init]);

	useEffect(() => {
		// Next js fix
		setSignClient(client);
	}, [client]);

	return (
		<>
			<Head>
				<title>Swip</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="flex min-h-screen flex-col items-center justify-center">
				<div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
					<p>WalletConnect</p>
					<p>Connection ok: {signClient ? "true" : "false"} </p>
					{signClient && <WalletConnectButton></WalletConnectButton>}
				</div>
			</main>
		</>
	);
}
